export const templates = [
  "cra",
  "cra_typescript",
  //  "react",
  //  "react_typescript",
  //  "webpack_react",
  //  "react_in_yarn_workspace",
  //  "angular10",
  //  "angular11",
  "angular",
  //  "web_components",
  //  "web_components_typescript",
  "web_components_lit2",
  //  "vue",
  "vue3",
  "html",
  "preact",
  //  "sfcVue",
  "svelte",
];
